admins/urls.py
from django.urls import path
from .views import *
app_name="admins"
urlpatterns=[
    path('admin-home/' , admin_home , name="admin-home"),
    path('users-view/' , users_view , name="users-view"),
    path('add-employee/' , add_employee , name="add-employee"),
    path('projects-view/' , projects_view , name="projects-view"),
    path('filterd-users/' , filterd_users , name="filterd-users"),
    path('filterd-projects/' , filterd_projects , name="filterd-projects"),
]

management/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("account.urls",namespace="account")),
    path('', include("employee.urls",namespace="employee")),
    path('', include("admins.urls",namespace="admins")),
    path('', include("manager.urls",namespace="manager")),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)+static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

admins/forms.py
from django import forms
from account.models import User
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.core.validators import validate_email


class UserForm(UserCreationForm):
    class Meta:
        model = User
        fields = ['username', 'email', 'mobile', 'role', 'password1', 'password2']

        widgets = {
            'username': forms.TextInput(attrs={'class': 'form-control'}),
            'email': forms.EmailInput(attrs={'class': 'form-control'}),
            'mobile': forms.TextInput(attrs={'class': 'form-control'}),
            'role': forms.Select(attrs={'class': 'form-control'}),
            'password1': forms.PasswordInput(attrs={'class': 'form-control'}),
            'password2': forms.PasswordInput(attrs={'class': 'form-control'}),
        }

    email = forms.CharField(validators=[validate_email])

templates/admins/add-employee.html
{% extends 'main/base.html' %}
{% block content %}
{% load static %}

<style>
    #id_email {
    width: 100% !important;
    /* Add any other styles you want */
}

</style>

    <div class="row justify-content-center">
        <div class="col-md-8 p-3 shadow">
            <div id="error-message" class="alert alert-danger d-none" role="alert"></div>
            <form method="POST" id="users-form">
                {% csrf_token %}
                {{form}}
                <button id="product-btn" class="btn btn-primary btn-block btn-lg shadow-lg mt-5">Submit</button>
            </form>    
        </div>
    </div>




    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.7.1/jquery.min.js"></script>
<link href="https://cdn.jsdelivr.net/npm/select2@4.1.0-rc.0/dist/css/select2.min.css" rel="stylesheet" />
<script src="https://cdn.jsdelivr.net/npm/select2@4.1.0-rc.0/dist/js/select2.min.js"></script>
<script>
    $(document).ready(function() {
        ///  sumbit the sell form
        $("#users-form").submit(function (e) {
            e.preventDefault();
            $.ajax({
                type: "POST",
                url: "{% url 'admins:add-employee' %}",
                data: $(this).serialize(),
                success: function (data) {
                    if (data.status === "success") {
                        window.location.href = "{% url 'admins:users-view' %}";
                    } else {
                        // Display the error message
                        let errorMessage=''
                        $(data.status).find('li').each(function () {
                            errorMessage += $(this).text() + '<br>';
                        });
                        $("#error-message").html(errorMessage).removeClass('d-none');
                        
                    }
                },
                error: function (xhr, textStatus, errorThrown) {
                    console.log(xhr.responseText);
                }
            });
        });

    });
</script>
{% endblock %}

templates/admins/projects.html
{% extends 'main/base.html' %}
{% block content %}
{% load static %}

<div class="page-heading">
    <div class="page-title">
        <div class="row">
            <div class="col-12 col-md-6 order-md-1 order-last">
                <h3>Company Projects </h3>
                <p class="text-subtitle text-muted"></p>
            </div>
            <div class="col-12 col-md-6 order-md-2 order-first">
                <nav aria-label="breadcrumb" class="breadcrumb-header float-start float-lg-end">
                    <ol class="breadcrumb">
                        <li class="breadcrumb-item"><a href="/">Dashboard</a></li>
                        <li class="breadcrumb-item active" aria-current="page">ProjectTable</li>
                    </ol>
                </nav>
            </div>
        </div>
    </div>
    <!-- Basic Tables start -->
    <section class="section">
        <div class="card">
            <div class="card-header">
                <div class="row justify-content-center">
                    <div class="col-6"> 
                        <select 
                        name="projects_status"
                        class="form-select form-select-sm" 
                        hx-get="{% url 'admins:filterd-projects' %}"
                        hx-trigger="change"
                        hx-target=".table"    
                        hx-swap = "outerHTML"
                        >
                            <option value="all">All</option>
                            <option value="active">Completed</option>
                            <option value="deactive">Not-Completed</option>
                        </select>
                    </div>    
                </div>
              
            </div>

            <div class="card-body">
                {% include 'admins/partials/projects.html' %}
            </div>
    </div>
    
    </section>
    <!-- Basic Tables end -->
</div>


{% endblock %}

templates/admins/users.html
{% extends 'main/base.html' %}
{% block content %}
{% load static %}

<div class="page-heading">
    <div class="page-title">
        <div class="row">
            <div class="col-12 col-md-6 order-md-1 order-last">
                <h3>Company Employees </h3>
                <p class="text-subtitle text-muted"></p>
            </div>
            <div class="col-12 col-md-6 order-md-2 order-first">
                <nav aria-label="breadcrumb" class="breadcrumb-header float-start float-lg-end">
                    <ol class="breadcrumb">
                        <li class="breadcrumb-item"><a href="/">Dashboard</a></li>
                        <li class="breadcrumb-item active" aria-current="page">EmployeeTable</li>
                    </ol>
                </nav>
            </div>
        </div>
    </div>
    <!-- Basic Tables start -->
    <section class="section">
        <div class="card">
            <div class="card-header">
                <a class="btn btn-primary" href="{% url 'admins:add-employee' %}" role="button">Add Employee</a>
                <div class="row justify-content-center">
                    <div class="col-6"> 
                        <select 
                        name="users_status"
                        class="form-select form-select-sm" 
                        hx-get="{% url 'admins:filterd-users' %}"
                        hx-trigger="change"
                        hx-target=".table"    
                        hx-swap = "outerHTML"
                        >
                            <option value="all">All</option>
                            <option value="active">Active</option>
                            <option value="deactive">Deactive</option>
                        </select>
                    </div>    



                </div>
              
            </div>

            <div class="card-body">
                {% include 'admins/partials/users.html' %}
            </div>
    </div>
    
    </section>
    <!-- Basic Tables end -->
</div>


{% endblock %}