admins/urls.py
from django.urls import path
from .views import *
app_name="admins"
urlpatterns=[
    path('admin-home/' , admin_home , name="admin-home"),
    path('users-view/' , users_view , name="users-view"),
    path('add-employee/' , add_employee , name="add-employee"),
    path('projects-view/' , projects_view , name="projects-view"),
    path('filterd-users/' , filterd_users , name="filterd-users"),
    path('filterd-projects/' , filterd_projects , name="filterd-projects"),
]

management/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("account.urls",namespace="account")),
    path('', include("employee.urls",namespace="employee")),
    path('', include("admins.urls",namespace="admins")),
    path('', include("manager.urls",namespace="manager")),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)+static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

manager/urls.py
from django.urls import path
from .views import *
app_name="manager"
urlpatterns=[
    path('manager-home/' , manager_home , name="manager-home"),
    path('manager-team/' , manager_team , name="manager-team"),
    path('manager-projects/' , manager_projects , name="manager-projects"),
    path('add-project/' , add_project , name="add-project"),
    path('add-team/' , add_team , name="add-team"),
    path('team-filter/' , team_filter , name="team-filter"),
    path('assign-task/<int:project_id>/<int:user_id>/' , assign_task , name="assign-task"),
]

manager/models.py
from django.db import models
from account.models import BaseClass


class Project(BaseClass):
    name        = models.CharField(max_length=255)
    description = models.TextField()
    start_date  = models.DateField()
    end_date    = models.DateField()
    manager     = models.ForeignKey("account.User", on_delete=models.CASCADE, limit_choices_to={'role': 'manager'},related_name="manager_project")
    is_completed = models.BooleanField(default=False)

    def __str__(self):
        return self.name

class Team(BaseClass):
    project = models.ForeignKey("manager.Project", on_delete=models.CASCADE , related_name="teamProjects")
    name = models.CharField(max_length=255)
    members = models.ManyToManyField("account.User", limit_choices_to={'role': 'employee'} , related_name="team_members")
    manager = models.ForeignKey("account.User", on_delete=models.CASCADE, limit_choices_to={'role': 'manager'},related_name="team_manager")

    def __str__(self):
        return self.name
    
class Task(BaseClass):
    title = models.CharField(max_length=255)
    description = models.TextField()
    deadline = models.DateField()
    priority = models.CharField(max_length=20, choices=[('High', 'High'), ('Medium', 'Medium'), ('Low', 'Low')])
    status = models.CharField(max_length=20, choices=[('Pending', 'Pending'), ('Completed', 'Completed')])
    assigned_to = models.ForeignKey("account.User", on_delete=models.CASCADE, limit_choices_to={'role': 'employee'} , related_name="my_task")
    project = models.ForeignKey("manager.Project", on_delete=models.CASCADE , related_name="emp_task")

    def __str__(self):
        return self.title
    
class Feedback(BaseClass):
    task = models.ForeignKey(Task, on_delete=models.CASCADE)
    feedback_text = models.TextField()
    created_by = models.ForeignKey("account.User", on_delete=models.CASCADE, limit_choices_to={'role': 'manager'})
    
    def __str__(self):
        return self.feedback_text

manager/forms.py
from django import forms
from account.models import User
from  manager.models import *
from django import forms


class ProjectForm(forms.ModelForm):
    class Meta:
        model = Project
        fields = ['name', 'description', 'start_date', 'end_date']
        widgets = {
                'name': forms.TextInput(attrs={'class': 'form-control'}),
                'description': forms.Textarea(attrs={'class': 'form-control'}),
                'start_date': forms.DateInput(format=('%Y-%m-%d'), attrs = {'class':'form-control', 'type':'date'}),
                'end_date': forms.DateInput(format=('%Y-%m-%d'), attrs = {'class':'form-control', 'type':'date'}),
            }


class TeamForm(forms.ModelForm):
    class Meta:
        model = Team
        fields = ['project', 'name', 'members']

        widgets = {
            'project': forms.Select(attrs={'class': 'form-control'}),
            'name': forms.TextInput(attrs={'class': 'form-control'}),
            'members': forms.SelectMultiple(attrs={'class': 'form-control'}),
        }

class AddTaskForm(forms.ModelForm):
    class Meta:
        model = Task
        fields = ['title', 'description', 'deadline', 'priority', 'status']

        widgets = {
            'title': forms.TextInput(attrs={'class': 'form-control'}),
            'description': forms.Textarea(attrs={'class': 'form-control'}),
            'deadline': forms.DateInput(attrs={'class': 'form-control', 'type': 'date'}),
            'priority': forms.Select(attrs={'class': 'form-control'}),
            'status': forms.Select(attrs={'class': 'form-control'})
        }

manager/views.py
from imports import *

@user_passes_test(lambda u: u.role == 'manager', login_url='/login/')
def manager_home(request):
    context={
        'teams': Team.objects.filter(manager=request.user).count(),
        'completed_projects': (Project.objects.filter(manager=request.user , is_completed=True).count()),
        'active_projects': (Project.objects.filter(manager=request.user , is_completed=False).count()),
    }
    return render(request,"main/home.html",context)

@user_passes_test(lambda u: u.role == 'manager', login_url='/login/')
def manager_projects(request):
    context={'projects': Project.objects.filter(manager=request.user).order_by('-created_at')}
    return render(request,"manager/manager-projects.html",context)


@user_passes_test(lambda u: u.role == 'manager', login_url='/login/')
def manager_team(request):
    context={'teams': Team.objects.filter(manager=request.user)}
    return render(request,"manager/manager-team.html",context)


@user_passes_test(lambda u: u.role == 'manager', login_url='/login/')
def add_project(request):
    if request.method == 'POST':
        form = ProjectForm(request.POST)
        if form.is_valid():
            project = form.save(commit=False)
            project.manager = request.user
            project.save()
            messages.success(request , "Project Added Succesfully")
            return JsonResponse({'status':"success"})
        else:
            return JsonResponse({'status':f'{form.errors}'})
    else:
        form = ProjectForm()
    return render(request, 'manager/add_project.html', {'form': form})


@user_passes_test(lambda u: u.role == 'manager', login_url='/login/')
def add_team(request):
    if request.method == 'POST':
        form = TeamForm(request.POST)
        if form.is_valid():
            getData= request.POST.getlist("members")
            team = form.save(commit=False)
            team.manager = request.user
            team.save()
            team.members.add(*getData) 
            messages.success(request, "Team Added Successfully")
            return JsonResponse({'status': "success"})
        else:
            return JsonResponse({'status': f'{form.errors}'})
    else:
        form = TeamForm()
    return render(request, 'manager/add-team.html', {'form': form})

@user_passes_test(lambda u: u.role == 'manager', login_url='/login/')
def assign_task(request , project_id , user_id):
    getUser=User.objects.get(id=user_id)
    getProj=Project.objects.get(id=project_id)
    
    if request.method == 'POST':
        form = AddTaskForm(request.POST)
        if form.is_valid():
            team = form.save(commit=False)
            team.manager = request.user
            team.assigned_to = getUser
            team.project = getProj
            team.save()
            messages.success(request, f"Task to {getUser.username} assigned Successfully")
            return JsonResponse({'status': "success"})
        else:
            return JsonResponse({'status': f'{form.errors}'})
        
    context={
        "form" : AddTaskForm(),
        "project_id": project_id,
        "user_id": user_id,
        "quote": f"Assin the task to {getUser.username} for {getProj.name}"
    }
  
    return render(request, 'manager/assign-task.html', context)


###############   Filters ###############

def team_filter(request):
    team_id=request.GET.get('team_id')
    
    if team_id != 'all_team':
        teams   = Team.objects.filter(manager=request.user , id=team_id)

    else:
        teams = Team.objects.filter(manager=request.user)

    return render(request , 'manager/partials/teams.html' , {'teams':teams}  )  
     

templates/manager/add-team.html
{% extends 'main/base.html' %}
{% block content %}
{% load static %}



    <div class="row justify-content-center">
        <div class="col-md-8 p-3 shadow">
            <div id="error-message" class="alert alert-danger d-none" role="alert"></div>
            <form method="POST" id="manager-form">
                {% csrf_token %}
                {{form}}
                <button id="product-btn" class="btn btn-primary btn-block btn-lg shadow-lg mt-5">Submit</button>
            </form>    
        </div>
    </div>




<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.7.1/jquery.min.js"></script>
<link href="https://cdn.jsdelivr.net/npm/select2@4.1.0-rc.0/dist/css/select2.min.css" rel="stylesheet" />
<script src="https://cdn.jsdelivr.net/npm/select2@4.1.0-rc.0/dist/js/select2.min.js"></script>
<script>
    $(document).ready(function() {
        ///  sumbit the sell form
        $("#manager-form").submit(function (e) {
            e.preventDefault();
            $.ajax({
                type: "POST",
                url: "{% url 'manager:add-team' %}",
                data: $(this).serialize(),
                success: function (data) {
                    if (data.status === "success") {
                        window.location.href = "{% url 'manager:manager-team' %}";
                    } else {
                        // Display the error message
                        console.log(data.status)
                        $("#error-message").text(data.status).removeClass('d-none');
                    }
                },
                error: function (xhr, textStatus, errorThrown) {
                    console.log(xhr.responseText);
                }
            });
        });

    });
</script>
{% endblock %}

templates/manager/add_project.html
{% extends 'main/base.html' %}
{% block content %}
{% load static %}



    <div class="row justify-content-center">
        <div class="col-md-8 p-3 shadow">
            <div id="error-message" class="alert alert-danger d-none" role="alert"></div>
            <form method="POST" id="manager-form">
                {% csrf_token %}
                {{form}}
                <button id="product-btn" class="btn btn-primary btn-block btn-lg shadow-lg mt-5">Submit</button>
            </form>    
        </div>
    </div>




<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.7.1/jquery.min.js"></script>
<link href="https://cdn.jsdelivr.net/npm/select2@4.1.0-rc.0/dist/css/select2.min.css" rel="stylesheet" />
<script src="https://cdn.jsdelivr.net/npm/select2@4.1.0-rc.0/dist/js/select2.min.js"></script>
<script>
    $(document).ready(function() {
        ///  sumbit the sell form
        $("#manager-form").submit(function (e) {
            e.preventDefault();
            $.ajax({
                type: "POST",
                url: "{% url 'manager:add-project' %}",
                data: $(this).serialize(),
                success: function (data) {
                    if (data.status === "success") {
                        window.location.href = "{% url 'manager:manager-projects' %}";
                    } else {
                        // Display the error message
                        console.log(data.status)
                        $("#error-message").text(data.status).removeClass('d-none');
                    }
                },
                error: function (xhr, textStatus, errorThrown) {
                    console.log(xhr.responseText);
                }
            });
        });

    });
</script>
{% endblock %}

templates/manager/assign-task.html
{% extends 'main/base.html' %}
{% block content %}
{% load static %}



    <div class="row justify-content-center">
        <div class="col-md-8 p-3 shadow">
            <div id="error-message" class="alert alert-danger d-none" role="alert"></div>
            <div >
                <h3>{{quote}}</h3>
            </div>
            <form method="POST" id="manager-form">
                {% csrf_token %}
                {{form}}
                <button id="product-btn" class="btn btn-primary btn-block btn-lg shadow-lg mt-5">Submit</button>
            </form>    
        </div>
    </div>


<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.7.1/jquery.min.js"></script>
<link href="https://cdn.jsdelivr.net/npm/select2@4.1.0-rc.0/dist/css/select2.min.css" rel="stylesheet" />
<script src="https://cdn.jsdelivr.net/npm/select2@4.1.0-rc.0/dist/js/select2.min.js"></script>
<script>
    $(document).ready(function() {
        ///  sumbit the sell form
        var project_id = {{ project_id }};
        var user_id = {{ user_id }};
        $("#manager-form").submit(function (e) {
            e.preventDefault();
            $.ajax({
                type: "POST",
                url: "{% url 'manager:assign-task' project_id=project_id user_id=user_id %}",
                data: $(this).serialize(),
                success: function (data) {
                    if (data.status === "success") {
                        window.location.href = "{% url 'manager:manager-team' %}";
                    } else {
                        // Display the error message
                        console.log(data.status)
                        $("#error-message").text(data.status).removeClass('d-none');
                    }
                },
                error: function (xhr, textStatus, errorThrown) {
                    console.log(xhr.responseText);
                }
            });
        });

    });
</script>
{% endblock %}

templates/manager/manager-projects.html
{% extends 'main/base.html' %}
{% block content %}
{% load static %}

<div class="page-heading">
    <div class="page-title">
        <div class="row">
            <div class="col-12 col-md-6 order-md-1 order-last">
                <h3>Company Projects </h3>
                <p class="text-subtitle text-muted"></p>
            </div>
            <div class="col-12 col-md-6 order-md-2 order-first">
                <nav aria-label="breadcrumb" class="breadcrumb-header float-start float-lg-end">
                    <ol class="breadcrumb">
                        <li class="breadcrumb-item"><a href="/">Dashboard</a></li>
                        <li class="breadcrumb-item active" aria-current="page">ProjectTable</li>
                    </ol>
                </nav>
            </div>
        </div>
    </div>
    <!-- Basic Tables start -->
    <section class="section">
        <div class="card">
            <div class="card-header">
                <a class="btn btn-primary" href="{% url 'manager:add-project' %}" role="button">Add Project</a>
                <div class="row justify-content-center">
                    <div class="col-6"> 
                        <select 
                        name="manager_projects"
                        class="form-select form-select-sm" 
                        hx-get="{% url 'admins:filterd-projects' %}"
                        hx-trigger="change"
                        hx-target=".table"    
                        hx-swap = "outerHTML"
                        >
                            <option value="all">All</option>
                            <option value="active">Completed</option>
                            <option value="deactive">Not-Completed</option>
                        </select>
                    </div>    
                </div>
              
            </div>

            <div class="card-body">
                {% include 'manager/partials/projects.html' %}
            </div>
    </div>
    
    </section>
    <!-- Basic Tables end -->
</div>
{% endblock %}

templates/manager/manager-team.html
{% extends 'main/base.html' %}
{% block content %}
{% load static %}

<div class="page-heading">
    <div class="page-title">
        <div class="row">
            <div class="col-12 col-md-6 order-md-1 order-last">
                <h3>My Teams </h3>
                <p class="text-subtitle text-muted"></p>
            </div>
            <div class="col-12 col-md-6 order-md-2 order-first">
                <nav aria-label="breadcrumb" class="breadcrumb-header float-start float-lg-end">
                    <ol class="breadcrumb">
                        <li class="breadcrumb-item"><a href="/">Dashboard</a></li>
                        <li class="breadcrumb-item active" aria-current="page">ProjectTable</li>
                    </ol>
                </nav>
            </div>
        </div>
    </div>
    <!-- Basic Tables start -->
    <section class="section">
        <div class="card">
            <div class="card-header">
                <a class="btn btn-primary" href="{% url 'manager:add-team' %}" role="button">Add Team</a>
                <div class="row justify-content-center">
                    <div class="col-6"> 
                        <select 
                            name="team_id"
                            class="form-select form-select-sm" 
                            hx-get="{% url 'manager:team-filter' %}"
                            hx-trigger="change"
                            hx-target=".table"    
                            hx-swap = "outerHTML"
                        >
                            <option value="all_team">All</option>
                            {% for i in teams %}
                            <option value="{{i.id}}">{{i.name}}</option>
                            {% endfor %}
                           
                        </select>
                    </div>    
                </div>
              
            </div>

            <div class="card-body">
                {% include 'manager/partials/teams.html' %}
            </div>
    </div>
    
    </section>
    <!-- Basic Tables end -->
</div>

{% endblock %}