account/urls.py
from django.urls import path
from .views import *

app_name="account"

urlpatterns=[
    path("" , home , name="home"),
    path("login/" , login_view , name="login"),
    path("logout_view/" , logout_view , name="logout_view"),
    path("my-notification/" , my_notifications , name="my-notification"),
]

admins/urls.py
from django.urls import path
from .views import *
app_name="admins"
urlpatterns=[
    path('admin-home/' , admin_home , name="admin-home"),
    path('users-view/' , users_view , name="users-view"),
    path('add-employee/' , add_employee , name="add-employee"),
    path('projects-view/' , projects_view , name="projects-view"),
    path('filterd-users/' , filterd_users , name="filterd-users"),
    path('filterd-projects/' , filterd_projects , name="filterd-projects"),
]

employee/urls.py
from django.urls import path
from .views import *
app_name="employee"

urlpatterns=[

    path("employee-home/" , employee_home , name="employee-home"),
    path("employee-task/" , employee_task , name="employee-task"),
    path("employee-filterd/" , employee_filtered , name="employee-filterd"),
    path("update-task/<int:pk>/" , update_task , name="update-task"),
]

management/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("account.urls",namespace="account")),
    path('', include("employee.urls",namespace="employee")),
    path('', include("admins.urls",namespace="admins")),
    path('', include("manager.urls",namespace="manager")),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)+static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

manager/urls.py
from django.urls import path
from .views import *
app_name="manager"
urlpatterns=[
    path('manager-home/' , manager_home , name="manager-home"),
    path('manager-team/' , manager_team , name="manager-team"),
    path('manager-projects/' , manager_projects , name="manager-projects"),
    path('add-project/' , add_project , name="add-project"),
    path('add-team/' , add_team , name="add-team"),
    path('team-filter/' , team_filter , name="team-filter"),
    path('assign-task/<int:project_id>/<int:user_id>/' , assign_task , name="assign-task"),
]

templates/main/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Dashboard</title>
    <link rel="preconnect" href="https://fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css2?family=Nunito:wght@300;400;600;700;800&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="{% static 'assets/css/bootstrap.css' %}">
    <link rel="stylesheet" href="{% static 'assets/vendors/iconly/bold.css' %}">
    <link rel="stylesheet" href="{% static 'assets/vendors/perfect-scrollbar/perfect-scrollbar.css' %}">
    <link rel="stylesheet" href="{% static 'assets/vendors/bootstrap-icons/bootstrap-icons.css' %}">
    <link rel="stylesheet" href="{% static 'assets/css/app.css' %}">
    <link rel="shortcut icon" href="assets/images/favicon.svg" type="image/x-icon">
 <!-- htmx cdn -->
 <script src="https://unpkg.com/htmx.org@1.9.6" integrity="sha384-FhXw7b6AlE/jyjlZH5iHa/tTe9EpJ1Y55RjcgPbjeWMskSxZt1v9qkxLJWNJaGni" crossorigin="anonymous"></script>
 <!-- htmx websocket -->
 <script src="https://unpkg.com/htmx.org/dist/ext/ws.js"></script>

</head>
<body hx-ext="ws" ws-connect="/ws/notifications/">
<div id="app">
    <div id="sidebar" class="active">
        <div class="sidebar-wrapper active">
            <div class="sidebar-header">
                <div class="d-flex justify-content-between">
                    <div class="logo">
                        <a href="/">{% if request.user.username %}{{request.user.username}}{% else %} Admin {% endif %}</a>
                    </div>
                    <div class="toggler">
                        <a href="#" class="sidebar-hide d-xl-none d-block"><i class="bi bi-x bi-middle"></i></a>
                    </div>
                </div>
            </div>
            <div class="sidebar-menu">
                <ul class="menu">
                    <li class="sidebar-title">Menu</li>
                      
            {% if request.user.role == "admin" %}      
                    <li
                        class="sidebar-item active ">
                        <a href="{% url 'admins:admin-home'%}" class='sidebar-link'>
                            <i class="bi bi-grid-fill"></i>
                            <span>Dashboard</span>
                        </a>
                    </li>   
                    <li
                        class="sidebar-item  ">
                        <a href="{% url 'admins:users-view' %}" class='sidebar-link'>
                            <i class="bi bi-life-preserver"></i>
                            <span>Employees</span>
                        </a>
                    </li>

                    <li
                    class="sidebar-item  ">
                    <a href="{% url 'admins:projects-view' %}" class='sidebar-link'>
                        <i class="bi bi-cash"></i>
                        <span>Projects</span>
                    </a>
                    </li>
                    

            {% elif request.user.role == "manager" %}
                        <li
                        class="sidebar-item active ">
                        <a href="{% url 'manager:manager-home'%}" class='sidebar-link'>
                            <i class="bi bi-grid-fill"></i>
                            <span>Dashboard</span>
                        </a>
                    </li>  
                    <li
                    class="sidebar-item  ">
                    <a href="{% url 'manager:manager-projects'%}" class='sidebar-link'>
                        <i class="bi bi-cash"></i>
                        <span> Projects </span>
                    </a>
                </li>

                <li
                    class="sidebar-item  ">
                    <a href="{% url 'manager:manager-team'%}" class='sidebar-link'>
                        <i class="bi bi-cash"></i>
                        <span> Team </span>
                    </a>
                </li>

            {% elif request.user.role == "employee" %}
                        <li
                        class="sidebar-item active ">
                        <a href="{% url 'employee:employee-home'%}" class='sidebar-link'>
                            <i class="bi bi-grid-fill"></i>
                            <span>Dashboard</span>
                        </a>
                    </li>  
                    
                    <li
                        class="sidebar-item  ">
                        <a href="{% url 'employee:employee-task' %}" class='sidebar-link'>
                            <i class="bi bi-cash"></i>
                            <span> 
                             My Tasks
                            </span>
                        </a>
                    </li>
            {% endif %}
            <li class="sidebar-item">
                <a href="{% url 'account:my-notification' %}" class='sidebar-link'>
                    <i class="bi bi-cash"></i>
                    <span>Notification</span>
                </a>
            </li>
                <li class="sidebar-item">
                    <a href="{% url 'account:logout_view' %}" class='sidebar-link'>
                        <i class="bi bi-cash"></i>
                        <span>Logout</span>
                    </a>
                </li>

               
                 
                {% include 'main/partials/notification.html' %}
                </ul>
            </div>
            <button class="sidebar-toggler btn x"><i data-feather="x"></i></button>
        </div>
    </div>
    
    <div id="main">
        <header class="mb-3">
            <a href="#" class="burger-btn d-block d-xl-none">
                <i class="bi bi-justify fs-3"></i>
            </a>
        </header>
            
        <div class="page-heading">
            {% if messages %}
            <div class="row justify-content-center">
                <div class="col-md-8">
                    {% for i in messages %} 
                    <div class="alert alert-success alert-dismissible fade show" role="alert">
                        <strong>{{i.message}}</strong>
                        <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
                    </div>
                    {% endfor %}
                </div>
            </div>
            {% endif %}
            {% block content %}
            {% endblock content %}
        </div>
       
        
        <footer>
            <div class="footer clearfix mb-0 text-muted">
                <div class="float-start">
                    <p>2024 &copy; Management</p>
                </div>
                <div class="float-end">
                    <p> 
                        <span class="text-danger">
                            <i class="bi bi-heart"></i>
                        </span>
                        <a href=""></a>
                    </p>
                </div>
            </div>
        </footer>
    </div>
</div>

<script src="{% static 'assets/vendors/perfect-scrollbar/perfect-scrollbar.min.js' %}"></script>
<script src="{% static 'assets/js/bootstrap.bundle.min.js' %}"></script>
    
<script src="{% static 'assets/vendors/apexcharts/apexcharts.js' %}"></script>
<script src="{% static 'assets/js/pages/dashboard.js' %}"></script>
<script src="{% static 'assets/js/mazer.js' %}"></script>

</body>
</html>

templates/main/home.html
{% extends 'main/base.html' %}
{% block content %}
{% load static %}

<div class="page-content">
    <section class="row">
        <div class="col-12">
            <div class="row">
                {% if request.user.role == "admin" %}
                <div class="col-6 col-lg-3 col-md-6">
                    <div class="card">
                        <div class="card-body px-3 py-4-5">
                            <div class="row">
                                <div class="col-md-4">
                                    <div class="stats-icon purple">
                                        <i class="iconly-boldProfile"></i>
                                    </div>
                                </div>
                                <div class="col-md-8">
                                    <h6 class="text-muted font-semibold">Employees</h6>
                                    <h6 class="font-extrabold mb-0">{{employees}}</h6>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="col-6 col-lg-3 col-md-6">
                    <div class="card">
                        <div class="card-body px-3 py-4-5">
                            <div class="row">
                                <div class="col-md-4">
                                    <div class="stats-icon blue">
                                        <i class="iconly-boldBookmark"></i>
                                    </div>
                                </div>
                                <div class="col-md-8">
                                    <h6 class="text-muted font-semibold">Active Projects</h6>
                                    <h6 class="font-extrabold mb-0">{{active_projects}}</h6>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="col-6 col-lg-3 col-md-6">
                    <div class="card">
                        <div class="card-body px-3 py-4-5">
                            <div class="row">
                                <div class="col-md-4">
                                    <div class="stats-icon green">
                                        <i class="iconly-boldBookmark"></i>
                                    </div>
                                </div>
                                <div class="col-md-8">
                                    <h6 class="text-muted font-semibold">Completed Projects</h6>
                                    <h6 class="font-extrabold mb-0">{{completed_projects}}</h6>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                {% elif request.user.role == "manager" %}
                    <div class="col-6 col-lg-3 col-md-6">
                        <div class="card">
                            <div class="card-body px-3 py-4-5">
                                <div class="row">
                                    <div class="col-md-4">
                                        <div class="stats-icon purple">
                                            <i class="iconly-boldProfile"></i>
                                        </div>
                                    </div>
                                    <div class="col-md-8">
                                        <h6 class="text-muted font-semibold">My Team</h6>
                                        <h6 class="font-extrabold mb-0">{{teams}}</h6>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="col-6 col-lg-3 col-md-6">
                        <div class="card">
                            <div class="card-body px-3 py-4-5">
                                <div class="row">
                                    <div class="col-md-4">
                                        <div class="stats-icon blue">
                                            <i class="iconly-boldBookmark"></i>
                                        </div>
                                    </div>
                                    <div class="col-md-8">
                                        <h6 class="text-muted font-semibold">Active Projects</h6>
                                        <h6 class="font-extrabold mb-0">{{active_projects}}</h6>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="col-6 col-lg-3 col-md-6">
                        <div class="card">
                            <div class="card-body px-3 py-4-5">
                                <div class="row">
                                    <div class="col-md-4">
                                        <div class="stats-icon green">
                                            <i class="iconly-boldBookmark"></i>
                                        </div>
                                    </div>
                                    <div class="col-md-8">
                                        <h6 class="text-muted font-semibold">Completed Projects</h6>
                                        <h6 class="font-extrabold mb-0">{{completed_projects}}</h6>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                    
                {% elif request.user.role == "employee" %}
                    
                    <div class="col-6 col-lg-3 col-md-6">
                        <div class="card">
                            <div class="card-body px-3 py-4-5">
                                <div class="row">
                                    <div class="col-md-4">
                                        <div class="stats-icon blue">
                                            <i class="iconly-boldBookmark"></i>
                                        </div>
                                    </div>
                                    <div class="col-md-8">
                                        <h6 class="text-muted font-semibold">Active Task</h6>
                                        <h6 class="font-extrabold mb-0">{{active_tasks}}</h6>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>

                    <div class="col-6 col-lg-3 col-md-6">
                        <div class="card">
                            <div class="card-body px-3 py-4-5">
                                <div class="row">
                                    <div class="col-md-4">
                                        <div class="stats-icon green">
                                            <i class="iconly-boldBookmark"></i>
                                        </div>
                                    </div>
                                    <div class="col-md-8">
                                        <h6 class="text-muted font-semibold">Completed Task</h6>
                                        <h6 class="font-extrabold mb-0">{{completed_tasks}}</h6>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                {% endif %}
            
            </div>
           
            
        </div>
      
    </section>

</div>


{% endblock %}

templates/main/notification.html
{% extends 'main/base.html' %}
{% block content %}
{% load static %}   
<div class="page-heading">
    <div class="page-title">
        <div class="row">
            <div class="col-12 col-md-6 order-md-1 order-last">
                <h3>My Notifications</h3>
                <p class="text-subtitle text-muted">After a week  notification will be delete automatically</p>
            </div>
            <div class="col-12 col-md-6 order-md-2 order-first">
                <nav aria-label="breadcrumb" class="breadcrumb-header float-start float-lg-end">
                    <ol class="breadcrumb">
                        <li class="breadcrumb-item"><a href="/">Dashboard</a></li>
                        <li class="breadcrumb-item active" aria-current="page">Alert</li>
                    </ol>
                </nav>
            </div>
        </div>
    </div>

    <section class="section">
        <div class="row">
            <div class="col-12">
                    {% for n in notifications %}
                        <div class="alert alert-secondary row justify-content-center">
                            <div class="col-10">
                                {{n.message}}
                            </div>
                            <div class="col-2">
                                <small>{{n.created_at}}</small>
                            </div>
                        </div>
                    {% endfor %}
            </div>
        </div>        
    </section>

</div>

{% endblock %}