admins/urls.py
from django.urls import path
from .views import *
app_name="admins"
urlpatterns=[
    path('admin-home/' , admin_home , name="admin-home"),
    path('users-view/' , users_view , name="users-view"),
    path('add-employee/' , add_employee , name="add-employee"),
    path('projects-view/' , projects_view , name="projects-view"),
    path('filterd-users/' , filterd_users , name="filterd-users"),
    path('filterd-projects/' , filterd_projects , name="filterd-projects"),
]

employee/urls.py
from django.urls import path
from .views import *
app_name="employee"

urlpatterns=[

    path("employee-home/" , employee_home , name="employee-home"),
    path("employee-task/" , employee_task , name="employee-task"),
    path("employee-filterd/" , employee_filtered , name="employee-filterd"),
    path("update-task/<int:pk>/" , update_task , name="update-task"),
]

management/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("account.urls",namespace="account")),
    path('', include("employee.urls",namespace="employee")),
    path('', include("admins.urls",namespace="admins")),
    path('', include("manager.urls",namespace="manager")),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)+static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

employee/models.py
from django.db import models

employee/forms.py
from django import forms
from manager.models import Task


class TaskForm(forms.ModelForm):
    class Meta:
        model = Task
        fields = ['status']
        
        widgets = {
            'status': forms.Select(attrs={'class': 'form-control'}),
        }

employee/views.py
from imports import *


@user_passes_test(lambda u: u.role == 'employee', login_url='/login/')
def employee_home(request):
    context={
        'active_tasks': Task.objects.filter(assigned_to=request.user , status="Pending").count(),
        'completed_tasks': Task.objects.filter(assigned_to=request.user,status="Completed").count()
    }
    return render(request,"main/home.html",context)


@user_passes_test(lambda u: u.role == 'employee', login_url='/login/')
def employee_task(request):
    context={
        'tasks': Task.objects.filter(assigned_to=request.user)
    }
    return render(request,"employee/tasks.html",context)



@user_passes_test(lambda u: u.role == 'employee', login_url='/login/')
def update_task(request,pk):
    obj=Task.objects.get(id=pk)
    form = TaskForm(instance=obj)
    if request.POST:
        form = TaskForm(request.POST , instance=obj)
        if form.is_valid():
            form.save()
            messages.success(request , f"{request.user.username} Status Updated Successfully")
            return redirect("employee:employee-task")
    context={'form':form , 'title':obj.title}
    return render(request,"employee/update-task.html",context)


def employee_filtered(request):
    get_status = request.GET.get('status', 'all_status')
    get_priority = request.GET.get('priority', 'all_priority')
    tasks = Task.objects.filter(assigned_to=request.user)
    if get_status != 'all_status':
        tasks = tasks.filter(status=get_status)

    if get_priority != 'all_priority':
        tasks = tasks.filter(priority=get_priority)

    return render(request, 'employee/partials/tasks.html', {'tasks': tasks})

templates/employee/tasks.html
{% extends 'main/base.html' %}
{% block content %}
{% load static %}

<div class="page-heading">
    <div class="page-title">
        <div class="row">
            <div class="col-12 col-md-6 order-md-1 order-last">
                <h3>MY Tasks </h3>
                <p class="text-subtitle text-muted"></p>
            </div>
            <div class="col-12 col-md-6 order-md-2 order-first">
                <nav aria-label="breadcrumb" class="breadcrumb-header float-start float-lg-end">
                    <ol class="breadcrumb">
                        <li class="breadcrumb-item"><a href="/">Dashboard</a></li>
                        <li class="breadcrumb-item active" aria-current="page">Task-Table</li>
                    </ol>
                </nav>
            </div>
        </div>
    </div>
    <!-- Basic Tables start -->
    <section class="section">
        <div class="card">
            <div class="card-header">
                <div class="row justify-content-center">
                    <div class="col-6"> 
                        <label for="">Status</label>
                        <select 
                        name="status"
                        class="form-select form-select-sm" 
                        hx-get="{% url 'employee:employee-filterd' %}"
                        hx-trigger="change"
                        hx-target=".table"    
                        hx-swap = "outerHTML"
                        >
                            <option value="all_status">All</option>
                            <option value="Pending">Pending</option>
                            <option value="Completed">Completed</option>
                        </select>
                    </div>    
                    <div class="col-6">
                        <label for="">Priority</label>
                        <select 
                        name="priority"
                        class="form-select form-select-sm" 
                        hx-get="{% url 'employee:employee-filterd' %}"
                        hx-trigger="change"
                        hx-target=".table"    
                        hx-swap = "outerHTML"
                        >
                            <option value="all_priority">All</option>
                            <option value="High">High</option>
                            <option value="Medium">Medium</option>
                            <option value="Low">Low</option>
                        </select>
                    </div>
                </div>
              
            </div>

            <div class="card-body">
                {% include 'employee/partials/tasks.html' %}
            </div>
    </div>
    
    </section>
    <!-- Basic Tables end -->
</div>
{% endblock %}

templates/employee/update-task.html
{% extends 'main/base.html' %}
{% block content %}
{% load static %}
    <div class="row justify-content-center">
        <div class="col-md-8 p-3 shadow">
            <div id="error-message" class="alert alert-danger d-none" role="alert"></div>
            <div >
                <h3>{{title}}</h3>
            </div>
            <form method="POST" id="manager-form">
                {% csrf_token %}
                {{form}}
                <button id="product-btn" class="btn btn-primary btn-block btn-lg shadow-lg mt-5">Submit</button>
            </form>    
        </div>
    </div>

{% endblock %}